
backend:
  name: git-gateway
  branch: main  # or whatever your main branch is (e.g., 'master')

media_folder: "static/img"  # where your images will go
public_folder: "/img"  # how the images are referenced in the public folder

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "content/blog"
    create: true  # allow creating new blog posts
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"  # format for post URLs
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
